//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRegistroServicio.wservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wservice.WSServicioSoap")]
    public interface WSServicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ValidarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar", ReplyAction="*")]
        WebRegistroServicio.wservice.ValidarResponse Validar(WebRegistroServicio.wservice.ValidarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRegistroServicio.wservice.ValidarResponse> ValidarAsync(WebRegistroServicio.wservice.ValidarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar", Namespace="http://tempuri.org/", Order=0)]
        public WebRegistroServicio.wservice.ValidarRequestBody Body;
        
        public ValidarRequest() {
        }
        
        public ValidarRequest(WebRegistroServicio.wservice.ValidarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ced;
        
        public ValidarRequestBody() {
        }
        
        public ValidarRequestBody(int ced) {
            this.ced = ced;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebRegistroServicio.wservice.ValidarResponseBody Body;
        
        public ValidarResponse() {
        }
        
        public ValidarResponse(WebRegistroServicio.wservice.ValidarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidarResult;
        
        public ValidarResponseBody() {
        }
        
        public ValidarResponseBody(string ValidarResult) {
            this.ValidarResult = ValidarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSServicioSoapChannel : WebRegistroServicio.wservice.WSServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSServicioSoapClient : System.ServiceModel.ClientBase<WebRegistroServicio.wservice.WSServicioSoap>, WebRegistroServicio.wservice.WSServicioSoap {
        
        public WSServicioSoapClient() {
        }
        
        public WSServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRegistroServicio.wservice.ValidarResponse WebRegistroServicio.wservice.WSServicioSoap.Validar(WebRegistroServicio.wservice.ValidarRequest request) {
            return base.Channel.Validar(request);
        }
        
        public string Validar(int ced) {
            WebRegistroServicio.wservice.ValidarRequest inValue = new WebRegistroServicio.wservice.ValidarRequest();
            inValue.Body = new WebRegistroServicio.wservice.ValidarRequestBody();
            inValue.Body.ced = ced;
            WebRegistroServicio.wservice.ValidarResponse retVal = ((WebRegistroServicio.wservice.WSServicioSoap)(this)).Validar(inValue);
            return retVal.Body.ValidarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRegistroServicio.wservice.ValidarResponse> WebRegistroServicio.wservice.WSServicioSoap.ValidarAsync(WebRegistroServicio.wservice.ValidarRequest request) {
            return base.Channel.ValidarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRegistroServicio.wservice.ValidarResponse> ValidarAsync(int ced) {
            WebRegistroServicio.wservice.ValidarRequest inValue = new WebRegistroServicio.wservice.ValidarRequest();
            inValue.Body = new WebRegistroServicio.wservice.ValidarRequestBody();
            inValue.Body.ced = ced;
            return ((WebRegistroServicio.wservice.WSServicioSoap)(this)).ValidarAsync(inValue);
        }
    }
}
