//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRegistroServicio.ServicioCitas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCitas.WSServicioSoap")]
    public interface WSServicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ced del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar", ReplyAction="*")]
        WebRegistroServicio.ServicioCitas.ValidarResponse Validar(WebRegistroServicio.ServicioCitas.ValidarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Validar", ReplyAction="*")]
        System.IAsyncResult BeginValidar(WebRegistroServicio.ServicioCitas.ValidarRequest request, System.AsyncCallback callback, object asyncState);
        
        WebRegistroServicio.ServicioCitas.ValidarResponse EndValidar(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar", Namespace="http://tempuri.org/", Order=0)]
        public WebRegistroServicio.ServicioCitas.ValidarRequestBody Body;
        
        public ValidarRequest() {
        }
        
        public ValidarRequest(WebRegistroServicio.ServicioCitas.ValidarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ced;
        
        public ValidarRequestBody() {
        }
        
        public ValidarRequestBody(string ced) {
            this.ced = ced;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebRegistroServicio.ServicioCitas.ValidarResponseBody Body;
        
        public ValidarResponse() {
        }
        
        public ValidarResponse(WebRegistroServicio.ServicioCitas.ValidarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidarResult;
        
        public ValidarResponseBody() {
        }
        
        public ValidarResponseBody(string ValidarResult) {
            this.ValidarResult = ValidarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSServicioSoapChannel : WebRegistroServicio.ServicioCitas.WSServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValidarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSServicioSoapClient : System.ServiceModel.ClientBase<WebRegistroServicio.ServicioCitas.WSServicioSoap>, WebRegistroServicio.ServicioCitas.WSServicioSoap {
        
        private BeginOperationDelegate onBeginValidarDelegate;
        
        private EndOperationDelegate onEndValidarDelegate;
        
        private System.Threading.SendOrPostCallback onValidarCompletedDelegate;
        
        public WSServicioSoapClient() {
        }
        
        public WSServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ValidarCompletedEventArgs> ValidarCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRegistroServicio.ServicioCitas.ValidarResponse WebRegistroServicio.ServicioCitas.WSServicioSoap.Validar(WebRegistroServicio.ServicioCitas.ValidarRequest request) {
            return base.Channel.Validar(request);
        }
        
        public string Validar(string ced) {
            WebRegistroServicio.ServicioCitas.ValidarRequest inValue = new WebRegistroServicio.ServicioCitas.ValidarRequest();
            inValue.Body = new WebRegistroServicio.ServicioCitas.ValidarRequestBody();
            inValue.Body.ced = ced;
            WebRegistroServicio.ServicioCitas.ValidarResponse retVal = ((WebRegistroServicio.ServicioCitas.WSServicioSoap)(this)).Validar(inValue);
            return retVal.Body.ValidarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebRegistroServicio.ServicioCitas.WSServicioSoap.BeginValidar(WebRegistroServicio.ServicioCitas.ValidarRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValidar(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginValidar(string ced, System.AsyncCallback callback, object asyncState) {
            WebRegistroServicio.ServicioCitas.ValidarRequest inValue = new WebRegistroServicio.ServicioCitas.ValidarRequest();
            inValue.Body = new WebRegistroServicio.ServicioCitas.ValidarRequestBody();
            inValue.Body.ced = ced;
            return ((WebRegistroServicio.ServicioCitas.WSServicioSoap)(this)).BeginValidar(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRegistroServicio.ServicioCitas.ValidarResponse WebRegistroServicio.ServicioCitas.WSServicioSoap.EndValidar(System.IAsyncResult result) {
            return base.Channel.EndValidar(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndValidar(System.IAsyncResult result) {
            WebRegistroServicio.ServicioCitas.ValidarResponse retVal = ((WebRegistroServicio.ServicioCitas.WSServicioSoap)(this)).EndValidar(result);
            return retVal.Body.ValidarResult;
        }
        
        private System.IAsyncResult OnBeginValidar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ced = ((string)(inValues[0]));
            return this.BeginValidar(ced, callback, asyncState);
        }
        
        private object[] OnEndValidar(System.IAsyncResult result) {
            string retVal = this.EndValidar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValidarCompleted(object state) {
            if ((this.ValidarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValidarCompleted(this, new ValidarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValidarAsync(string ced) {
            this.ValidarAsync(ced, null);
        }
        
        public void ValidarAsync(string ced, object userState) {
            if ((this.onBeginValidarDelegate == null)) {
                this.onBeginValidarDelegate = new BeginOperationDelegate(this.OnBeginValidar);
            }
            if ((this.onEndValidarDelegate == null)) {
                this.onEndValidarDelegate = new EndOperationDelegate(this.OnEndValidar);
            }
            if ((this.onValidarCompletedDelegate == null)) {
                this.onValidarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidarCompleted);
            }
            base.InvokeAsync(this.onBeginValidarDelegate, new object[] {
                        ced}, this.onEndValidarDelegate, this.onValidarCompletedDelegate, userState);
        }
    }
}
