//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteServicioWeb.Servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ValidarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar", ReplyAction="*")]
        ClienteServicioWeb.Servicio.ValidarResponse Validar(ClienteServicioWeb.Servicio.ValidarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteServicioWeb.Servicio.ValidarResponse> ValidarAsync(ClienteServicioWeb.Servicio.ValidarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicioWeb.Servicio.ValidarRequestBody Body;
        
        public ValidarRequest() {
        }
        
        public ValidarRequest(ClienteServicioWeb.Servicio.ValidarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ced;
        
        public ValidarRequestBody() {
        }
        
        public ValidarRequestBody(int ced) {
            this.ced = ced;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicioWeb.Servicio.ValidarResponseBody Body;
        
        public ValidarResponse() {
        }
        
        public ValidarResponse(ClienteServicioWeb.Servicio.ValidarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidarResult;
        
        public ValidarResponseBody() {
        }
        
        public ValidarResponseBody(string ValidarResult) {
            this.ValidarResult = ValidarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClienteServicioWeb.Servicio.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClienteServicioWeb.Servicio.WebService1Soap>, ClienteServicioWeb.Servicio.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteServicioWeb.Servicio.ValidarResponse ClienteServicioWeb.Servicio.WebService1Soap.Validar(ClienteServicioWeb.Servicio.ValidarRequest request) {
            return base.Channel.Validar(request);
        }
        
        public string Validar(int ced) {
            ClienteServicioWeb.Servicio.ValidarRequest inValue = new ClienteServicioWeb.Servicio.ValidarRequest();
            inValue.Body = new ClienteServicioWeb.Servicio.ValidarRequestBody();
            inValue.Body.ced = ced;
            ClienteServicioWeb.Servicio.ValidarResponse retVal = ((ClienteServicioWeb.Servicio.WebService1Soap)(this)).Validar(inValue);
            return retVal.Body.ValidarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteServicioWeb.Servicio.ValidarResponse> ClienteServicioWeb.Servicio.WebService1Soap.ValidarAsync(ClienteServicioWeb.Servicio.ValidarRequest request) {
            return base.Channel.ValidarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteServicioWeb.Servicio.ValidarResponse> ValidarAsync(int ced) {
            ClienteServicioWeb.Servicio.ValidarRequest inValue = new ClienteServicioWeb.Servicio.ValidarRequest();
            inValue.Body = new ClienteServicioWeb.Servicio.ValidarRequestBody();
            inValue.Body.ced = ced;
            return ((ClienteServicioWeb.Servicio.WebService1Soap)(this)).ValidarAsync(inValue);
        }
    }
}
