//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRegistroServicio.ServicioWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWS.WebServiceServicioSoap")]
    public interface WebServiceServicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ced del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar", ReplyAction="*")]
        WebRegistroServicio.ServicioWS.ValidarResponse Validar(WebRegistroServicio.ServicioWS.ValidarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Validar", ReplyAction="*")]
        System.IAsyncResult BeginValidar(WebRegistroServicio.ServicioWS.ValidarRequest request, System.AsyncCallback callback, object asyncState);
        
        WebRegistroServicio.ServicioWS.ValidarResponse EndValidar(System.IAsyncResult result);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarServicio", ReplyAction="*")]
        WebRegistroServicio.ServicioWS.InsertarServicioResponse InsertarServicio(WebRegistroServicio.ServicioWS.InsertarServicioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/InsertarServicio", ReplyAction="*")]
        System.IAsyncResult BeginInsertarServicio(WebRegistroServicio.ServicioWS.InsertarServicioRequest request, System.AsyncCallback callback, object asyncState);
        
        WebRegistroServicio.ServicioWS.InsertarServicioResponse EndInsertarServicio(System.IAsyncResult result);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ced del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarServicio", ReplyAction="*")]
        WebRegistroServicio.ServicioWS.MostrarServicioResponse MostrarServicio(WebRegistroServicio.ServicioWS.MostrarServicioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MostrarServicio", ReplyAction="*")]
        System.IAsyncResult BeginMostrarServicio(WebRegistroServicio.ServicioWS.MostrarServicioRequest request, System.AsyncCallback callback, object asyncState);
        
        WebRegistroServicio.ServicioWS.MostrarServicioResponse EndMostrarServicio(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar", Namespace="http://tempuri.org/", Order=0)]
        public WebRegistroServicio.ServicioWS.ValidarRequestBody Body;
        
        public ValidarRequest() {
        }
        
        public ValidarRequest(WebRegistroServicio.ServicioWS.ValidarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ced;
        
        public ValidarRequestBody() {
        }
        
        public ValidarRequestBody(string ced) {
            this.ced = ced;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebRegistroServicio.ServicioWS.ValidarResponseBody Body;
        
        public ValidarResponse() {
        }
        
        public ValidarResponse(WebRegistroServicio.ServicioWS.ValidarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ValidarResult;
        
        public ValidarResponseBody() {
        }
        
        public ValidarResponseBody(int ValidarResult) {
            this.ValidarResult = ValidarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarServicioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarServicio", Namespace="http://tempuri.org/", Order=0)]
        public WebRegistroServicio.ServicioWS.InsertarServicioRequestBody Body;
        
        public InsertarServicioRequest() {
        }
        
        public InsertarServicioRequest(WebRegistroServicio.ServicioWS.InsertarServicioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarServicioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ced;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int tipServ;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fecha;
        
        public InsertarServicioRequestBody() {
        }
        
        public InsertarServicioRequestBody(int ced, int tipServ, string fecha) {
            this.ced = ced;
            this.tipServ = tipServ;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarServicioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarServicioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebRegistroServicio.ServicioWS.InsertarServicioResponseBody Body;
        
        public InsertarServicioResponse() {
        }
        
        public InsertarServicioResponse(WebRegistroServicio.ServicioWS.InsertarServicioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarServicioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertarServicioResult;
        
        public InsertarServicioResponseBody() {
        }
        
        public InsertarServicioResponseBody(int InsertarServicioResult) {
            this.InsertarServicioResult = InsertarServicioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarServicioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarServicio", Namespace="http://tempuri.org/", Order=0)]
        public WebRegistroServicio.ServicioWS.MostrarServicioRequestBody Body;
        
        public MostrarServicioRequest() {
        }
        
        public MostrarServicioRequest(WebRegistroServicio.ServicioWS.MostrarServicioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarServicioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ced;
        
        public MostrarServicioRequestBody() {
        }
        
        public MostrarServicioRequestBody(string ced) {
            this.ced = ced;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarServicioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarServicioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebRegistroServicio.ServicioWS.MostrarServicioResponseBody Body;
        
        public MostrarServicioResponse() {
        }
        
        public MostrarServicioResponse(WebRegistroServicio.ServicioWS.MostrarServicioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarServicioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebRegistroServicio.ServicioWS.ArrayOfAnyType MostrarServicioResult;
        
        public MostrarServicioResponseBody() {
        }
        
        public MostrarServicioResponseBody(WebRegistroServicio.ServicioWS.ArrayOfAnyType MostrarServicioResult) {
            this.MostrarServicioResult = MostrarServicioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceServicioSoapChannel : WebRegistroServicio.ServicioWS.WebServiceServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValidarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertarServicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertarServicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MostrarServicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MostrarServicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebRegistroServicio.ServicioWS.ArrayOfAnyType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebRegistroServicio.ServicioWS.ArrayOfAnyType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceServicioSoapClient : System.ServiceModel.ClientBase<WebRegistroServicio.ServicioWS.WebServiceServicioSoap>, WebRegistroServicio.ServicioWS.WebServiceServicioSoap {
        
        private BeginOperationDelegate onBeginValidarDelegate;
        
        private EndOperationDelegate onEndValidarDelegate;
        
        private System.Threading.SendOrPostCallback onValidarCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertarServicioDelegate;
        
        private EndOperationDelegate onEndInsertarServicioDelegate;
        
        private System.Threading.SendOrPostCallback onInsertarServicioCompletedDelegate;
        
        private BeginOperationDelegate onBeginMostrarServicioDelegate;
        
        private EndOperationDelegate onEndMostrarServicioDelegate;
        
        private System.Threading.SendOrPostCallback onMostrarServicioCompletedDelegate;
        
        public WebServiceServicioSoapClient() {
        }
        
        public WebServiceServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ValidarCompletedEventArgs> ValidarCompleted;
        
        public event System.EventHandler<InsertarServicioCompletedEventArgs> InsertarServicioCompleted;
        
        public event System.EventHandler<MostrarServicioCompletedEventArgs> MostrarServicioCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRegistroServicio.ServicioWS.ValidarResponse WebRegistroServicio.ServicioWS.WebServiceServicioSoap.Validar(WebRegistroServicio.ServicioWS.ValidarRequest request) {
            return base.Channel.Validar(request);
        }
        
        public int Validar(string ced) {
            WebRegistroServicio.ServicioWS.ValidarRequest inValue = new WebRegistroServicio.ServicioWS.ValidarRequest();
            inValue.Body = new WebRegistroServicio.ServicioWS.ValidarRequestBody();
            inValue.Body.ced = ced;
            WebRegistroServicio.ServicioWS.ValidarResponse retVal = ((WebRegistroServicio.ServicioWS.WebServiceServicioSoap)(this)).Validar(inValue);
            return retVal.Body.ValidarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebRegistroServicio.ServicioWS.WebServiceServicioSoap.BeginValidar(WebRegistroServicio.ServicioWS.ValidarRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValidar(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginValidar(string ced, System.AsyncCallback callback, object asyncState) {
            WebRegistroServicio.ServicioWS.ValidarRequest inValue = new WebRegistroServicio.ServicioWS.ValidarRequest();
            inValue.Body = new WebRegistroServicio.ServicioWS.ValidarRequestBody();
            inValue.Body.ced = ced;
            return ((WebRegistroServicio.ServicioWS.WebServiceServicioSoap)(this)).BeginValidar(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRegistroServicio.ServicioWS.ValidarResponse WebRegistroServicio.ServicioWS.WebServiceServicioSoap.EndValidar(System.IAsyncResult result) {
            return base.Channel.EndValidar(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndValidar(System.IAsyncResult result) {
            WebRegistroServicio.ServicioWS.ValidarResponse retVal = ((WebRegistroServicio.ServicioWS.WebServiceServicioSoap)(this)).EndValidar(result);
            return retVal.Body.ValidarResult;
        }
        
        private System.IAsyncResult OnBeginValidar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ced = ((string)(inValues[0]));
            return this.BeginValidar(ced, callback, asyncState);
        }
        
        private object[] OnEndValidar(System.IAsyncResult result) {
            int retVal = this.EndValidar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValidarCompleted(object state) {
            if ((this.ValidarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValidarCompleted(this, new ValidarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValidarAsync(string ced) {
            this.ValidarAsync(ced, null);
        }
        
        public void ValidarAsync(string ced, object userState) {
            if ((this.onBeginValidarDelegate == null)) {
                this.onBeginValidarDelegate = new BeginOperationDelegate(this.OnBeginValidar);
            }
            if ((this.onEndValidarDelegate == null)) {
                this.onEndValidarDelegate = new EndOperationDelegate(this.OnEndValidar);
            }
            if ((this.onValidarCompletedDelegate == null)) {
                this.onValidarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidarCompleted);
            }
            base.InvokeAsync(this.onBeginValidarDelegate, new object[] {
                        ced}, this.onEndValidarDelegate, this.onValidarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRegistroServicio.ServicioWS.InsertarServicioResponse WebRegistroServicio.ServicioWS.WebServiceServicioSoap.InsertarServicio(WebRegistroServicio.ServicioWS.InsertarServicioRequest request) {
            return base.Channel.InsertarServicio(request);
        }
        
        public int InsertarServicio(int ced, int tipServ, string fecha) {
            WebRegistroServicio.ServicioWS.InsertarServicioRequest inValue = new WebRegistroServicio.ServicioWS.InsertarServicioRequest();
            inValue.Body = new WebRegistroServicio.ServicioWS.InsertarServicioRequestBody();
            inValue.Body.ced = ced;
            inValue.Body.tipServ = tipServ;
            inValue.Body.fecha = fecha;
            WebRegistroServicio.ServicioWS.InsertarServicioResponse retVal = ((WebRegistroServicio.ServicioWS.WebServiceServicioSoap)(this)).InsertarServicio(inValue);
            return retVal.Body.InsertarServicioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebRegistroServicio.ServicioWS.WebServiceServicioSoap.BeginInsertarServicio(WebRegistroServicio.ServicioWS.InsertarServicioRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertarServicio(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInsertarServicio(int ced, int tipServ, string fecha, System.AsyncCallback callback, object asyncState) {
            WebRegistroServicio.ServicioWS.InsertarServicioRequest inValue = new WebRegistroServicio.ServicioWS.InsertarServicioRequest();
            inValue.Body = new WebRegistroServicio.ServicioWS.InsertarServicioRequestBody();
            inValue.Body.ced = ced;
            inValue.Body.tipServ = tipServ;
            inValue.Body.fecha = fecha;
            return ((WebRegistroServicio.ServicioWS.WebServiceServicioSoap)(this)).BeginInsertarServicio(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRegistroServicio.ServicioWS.InsertarServicioResponse WebRegistroServicio.ServicioWS.WebServiceServicioSoap.EndInsertarServicio(System.IAsyncResult result) {
            return base.Channel.EndInsertarServicio(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndInsertarServicio(System.IAsyncResult result) {
            WebRegistroServicio.ServicioWS.InsertarServicioResponse retVal = ((WebRegistroServicio.ServicioWS.WebServiceServicioSoap)(this)).EndInsertarServicio(result);
            return retVal.Body.InsertarServicioResult;
        }
        
        private System.IAsyncResult OnBeginInsertarServicio(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int ced = ((int)(inValues[0]));
            int tipServ = ((int)(inValues[1]));
            string fecha = ((string)(inValues[2]));
            return this.BeginInsertarServicio(ced, tipServ, fecha, callback, asyncState);
        }
        
        private object[] OnEndInsertarServicio(System.IAsyncResult result) {
            int retVal = this.EndInsertarServicio(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertarServicioCompleted(object state) {
            if ((this.InsertarServicioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertarServicioCompleted(this, new InsertarServicioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertarServicioAsync(int ced, int tipServ, string fecha) {
            this.InsertarServicioAsync(ced, tipServ, fecha, null);
        }
        
        public void InsertarServicioAsync(int ced, int tipServ, string fecha, object userState) {
            if ((this.onBeginInsertarServicioDelegate == null)) {
                this.onBeginInsertarServicioDelegate = new BeginOperationDelegate(this.OnBeginInsertarServicio);
            }
            if ((this.onEndInsertarServicioDelegate == null)) {
                this.onEndInsertarServicioDelegate = new EndOperationDelegate(this.OnEndInsertarServicio);
            }
            if ((this.onInsertarServicioCompletedDelegate == null)) {
                this.onInsertarServicioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertarServicioCompleted);
            }
            base.InvokeAsync(this.onBeginInsertarServicioDelegate, new object[] {
                        ced,
                        tipServ,
                        fecha}, this.onEndInsertarServicioDelegate, this.onInsertarServicioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRegistroServicio.ServicioWS.MostrarServicioResponse WebRegistroServicio.ServicioWS.WebServiceServicioSoap.MostrarServicio(WebRegistroServicio.ServicioWS.MostrarServicioRequest request) {
            return base.Channel.MostrarServicio(request);
        }
        
        public WebRegistroServicio.ServicioWS.ArrayOfAnyType MostrarServicio(string ced) {
            WebRegistroServicio.ServicioWS.MostrarServicioRequest inValue = new WebRegistroServicio.ServicioWS.MostrarServicioRequest();
            inValue.Body = new WebRegistroServicio.ServicioWS.MostrarServicioRequestBody();
            inValue.Body.ced = ced;
            WebRegistroServicio.ServicioWS.MostrarServicioResponse retVal = ((WebRegistroServicio.ServicioWS.WebServiceServicioSoap)(this)).MostrarServicio(inValue);
            return retVal.Body.MostrarServicioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebRegistroServicio.ServicioWS.WebServiceServicioSoap.BeginMostrarServicio(WebRegistroServicio.ServicioWS.MostrarServicioRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMostrarServicio(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMostrarServicio(string ced, System.AsyncCallback callback, object asyncState) {
            WebRegistroServicio.ServicioWS.MostrarServicioRequest inValue = new WebRegistroServicio.ServicioWS.MostrarServicioRequest();
            inValue.Body = new WebRegistroServicio.ServicioWS.MostrarServicioRequestBody();
            inValue.Body.ced = ced;
            return ((WebRegistroServicio.ServicioWS.WebServiceServicioSoap)(this)).BeginMostrarServicio(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRegistroServicio.ServicioWS.MostrarServicioResponse WebRegistroServicio.ServicioWS.WebServiceServicioSoap.EndMostrarServicio(System.IAsyncResult result) {
            return base.Channel.EndMostrarServicio(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WebRegistroServicio.ServicioWS.ArrayOfAnyType EndMostrarServicio(System.IAsyncResult result) {
            WebRegistroServicio.ServicioWS.MostrarServicioResponse retVal = ((WebRegistroServicio.ServicioWS.WebServiceServicioSoap)(this)).EndMostrarServicio(result);
            return retVal.Body.MostrarServicioResult;
        }
        
        private System.IAsyncResult OnBeginMostrarServicio(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ced = ((string)(inValues[0]));
            return this.BeginMostrarServicio(ced, callback, asyncState);
        }
        
        private object[] OnEndMostrarServicio(System.IAsyncResult result) {
            WebRegistroServicio.ServicioWS.ArrayOfAnyType retVal = this.EndMostrarServicio(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMostrarServicioCompleted(object state) {
            if ((this.MostrarServicioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MostrarServicioCompleted(this, new MostrarServicioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MostrarServicioAsync(string ced) {
            this.MostrarServicioAsync(ced, null);
        }
        
        public void MostrarServicioAsync(string ced, object userState) {
            if ((this.onBeginMostrarServicioDelegate == null)) {
                this.onBeginMostrarServicioDelegate = new BeginOperationDelegate(this.OnBeginMostrarServicio);
            }
            if ((this.onEndMostrarServicioDelegate == null)) {
                this.onEndMostrarServicioDelegate = new EndOperationDelegate(this.OnEndMostrarServicio);
            }
            if ((this.onMostrarServicioCompletedDelegate == null)) {
                this.onMostrarServicioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMostrarServicioCompleted);
            }
            base.InvokeAsync(this.onBeginMostrarServicioDelegate, new object[] {
                        ced}, this.onEndMostrarServicioDelegate, this.onMostrarServicioCompletedDelegate, userState);
        }
    }
}
